name: cvv
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.5.0=h7ea286d_0
  - bzip2=1.0.8=h3422bc3_4
  - c-ares=1.18.1=h3422bc3_0
  - ca-certificates=2022.9.24=h4653dfc_0
  - cairo=1.16.0=h73a0509_1014
  - expat=2.5.0=hb7217d7_0
  - ffmpeg=5.1.2=gpl_hf4c414c_103
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=hab24e00_0
  - fontconfig=2.14.1=h82840c6_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hd633e50_0
  - gettext=0.21.1=h0186832_0
  - gmp=6.2.1=h9f76cd9_0
  - gnutls=3.7.8=h9f1a10d_0
  - graphite2=1.3.13=h9f76cd9_1001
  - harfbuzz=5.3.0=hddbc195_0
  - hdf5=1.12.2=nompi_h33dac16_100
  - icu=70.1=h6b3803e_0
  - jasper=2.0.33=hba35424_0
  - jpeg=9e=he4db4b2_2
  - krb5=1.19.3=he492e65_0
  - lame=3.100=h1a8c8d9_1003
  - lerc=4.0.0=h9a09cb3_0
  - libblas=3.9.0=16_osxarm64_openblas
  - libcblas=3.9.0=16_osxarm64_openblas
  - libcurl=7.86.0=h1c293e1_1
  - libcxx=14.0.6=h2692d47_0
  - libdeflate=1.14=h1a8c8d9_0
  - libedit=3.1.20191231=hc8eb9b7_2
  - libev=4.33=h642e427_1
  - libffi=3.4.2=h3422bc3_5
  - libgfortran=5.0.0=11_3_0_hd922786_26
  - libgfortran5=11.3.0=hdaf2cc0_26
  - libglib=2.74.1=h4646484_1
  - libiconv=1.17=he4db4b2_0
  - libidn2=2.3.4=h1a8c8d9_0
  - liblapack=3.9.0=16_osxarm64_openblas
  - liblapacke=3.9.0=16_osxarm64_openblas
  - libnghttp2=1.47.0=h519802c_1
  - libopenblas=0.3.21=openmp_hc731615_3
  - libopencv=4.6.0=py38h6e4ee2f_6
  - libpng=1.6.38=h76d750c_0
  - libprotobuf=3.21.9=hb5ab8b9_0
  - libsqlite=3.40.0=h76d750c_0
  - libssh2=1.10.0=h7a5bd25_3
  - libtasn1=4.19.0=h1a8c8d9_0
  - libtiff=4.4.0=hfa0b094_4
  - libunistring=0.9.10=h3422bc3_0
  - libvpx=1.11.0=hc470f4d_3
  - libwebp-base=1.2.4=h57fd34a_0
  - libxml2=2.10.3=h87b0503_0
  - libzlib=1.2.13=h03a7124_4
  - llvm-openmp=15.0.5=h7cfbb63_0
  - ncurses=6.3=h07bb92c_1
  - nettle=3.8.1=h63371fa_1
  - numpy=1.23.4=py38h09ac2d9_1
  - opencv=4.6.0=py38h150bfb4_6
  - openh264=2.3.1=hb7217d7_1
  - openssl=3.0.7=h03a7124_0
  - p11-kit=0.24.1=h29577a5_0
  - pcre2=10.40=hb34f9b4_0
  - pip=22.3.1=pyhd8ed1ab_0
  - pixman=0.40.0=h27ca646_0
  - py-opencv=4.6.0=py38hfbcc8b7_6
  - python=3.8.13=hd3575e6_0_cpython
  - python_abi=3.8=2_cp38
  - readline=8.1.2=h46ed386_0
  - setuptools=65.5.1=pyhd8ed1ab_0
  - sqlite=3.40.0=h2229b38_0
  - svt-av1=1.3.0=h7ea286d_0
  - tk=8.6.12=he1e0b03_0
  - wheel=0.38.4=pyhd8ed1ab_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xz=5.2.6=h57fd34a_0
  - zlib=1.2.13=h03a7124_4
  - zstd=1.5.2=h8128057_4
  - pip:
      - certifi==2023.7.22
      - charset-normalizer==3.3.2
      - idna==3.4
      - pillow==10.1.0
      - requests==2.31.0
      - urllib3==2.0.7
